<?php
/**
 * Admin settings page for ReviewApp.
 *
 * @package ReviewApp
 */

namespace ReviewApp\Admin;

use ReviewApp\Api\Client;

/**
 * Admin settings page.
 */
class Settings {

	/**
	 * Add admin menu.
	 */
	public function add_admin_menu() {
		add_options_page(
			__( 'ReviewApp Settings', 'reviewapp-reviews' ),
			__( 'ReviewApp', 'reviewapp-reviews' ),
			'manage_options',
			'reviewapp-settings',
			array( $this, 'render_settings_page' )
		);
	}



	/**
	 * Enqueue admin scripts and styles.
	 */
	public function enqueue_scripts( $hook ) {
		if ( 'settings_page_reviewapp-settings' !== $hook ) {
			return;
		}

		// Load asset dependencies from .asset.php file generated by @wordpress/scripts
		$asset_file = REVIEWAPP_PLUGIN_DIR . 'assets/build/admin.asset.php';
		$asset_data = file_exists( $asset_file ) ? include $asset_file : array( 'dependencies' => array(), 'version' => REVIEWAPP_VERSION );

		wp_enqueue_script(
			'reviewapp-admin',
			REVIEWAPP_PLUGIN_URL . 'assets/build/admin.js',
			$asset_data['dependencies'],
			$asset_data['version'],
			true
		);

		wp_localize_script(
			'reviewapp-admin',
			'reviewappAdmin',
			array(
				'restUrl'   => rest_url( 'reviewapp/v1' ),
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'apiUrl'    => reviewapp_get_api_url(),
				'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
			)
		);

		wp_enqueue_style(
			'reviewapp-admin',
			REVIEWAPP_PLUGIN_URL . 'assets/build/admin.css',
			array(),
			$asset_data['version']
		);
	}

	/**
	 * Render the settings page.
	 */
	public function render_settings_page() {
		?>
		<div class="wrap">
			<div id="reviewapp-settings-root"></div>
		</div>
		<?php
	}

}