<?php
/**
 * Admin settings page for ReviewApp.
 *
 * @package ReviewApp
 */

namespace ReviewApp\Admin;

use ReviewApp\Api\Client;

/**
 * Admin settings page.
 */
class Settings {

	/**
	 * Initialize admin hooks.
	 */
	public function __construct() {
		add_action( 'wp_ajax_reviewapp_update_schema_setting', array( $this, 'handle_schema_setting_update' ) );
	}

	/**
	 * Add admin menu.
	 */
	public function add_admin_menu() {
		add_options_page(
			__( 'ReviewApp Settings', 'reviewapp-reviews' ),
			__( 'ReviewApp', 'reviewapp-reviews' ),
			'manage_options',
			'reviewapp-settings',
			array( $this, 'render_settings_page' )
		);
	}



	/**
	 * Enqueue admin scripts and styles.
	 */
	public function enqueue_scripts( $hook ) {
		if ( 'settings_page_reviewapp-settings' !== $hook ) {
			return;
		}

		// Load asset dependencies from .asset.php file generated by @wordpress/scripts
		$asset_file = REVIEWAPP_PLUGIN_DIR . 'assets/build/admin.asset.php';
		$asset_data = file_exists( $asset_file ) ? include $asset_file : array( 'dependencies' => array(), 'version' => REVIEWAPP_VERSION );

		wp_enqueue_script(
			'reviewapp-admin',
			REVIEWAPP_PLUGIN_URL . 'assets/build/admin.js',
			$asset_data['dependencies'],
			$asset_data['version'],
			true
		);

		wp_localize_script(
			'reviewapp-admin',
			'reviewappAdmin',
			array(
				'restUrl'      => rest_url( 'reviewapp/v1' ),
				'nonce'        => wp_create_nonce( 'reviewapp_admin_nonce' ),
				'apiUrl'       => reviewapp_get_api_url(),
				'ajaxUrl'      => admin_url( 'admin-ajax.php' ),
				'enableSchema' => get_option( 'reviewapp_enable_schema', 'yes' ) === 'yes',
			)
		);

		wp_enqueue_style(
			'reviewapp-admin',
			REVIEWAPP_PLUGIN_URL . 'assets/build/admin.css',
			array(),
			$asset_data['version']
		);
	}

	/**
	 * Render the settings page.
	 */
	public function render_settings_page() {
		?>
		<div class="wrap">
			<div id="reviewapp-settings-root"></div>
		</div>
		<?php
	}

	/**
	 * Handle AJAX request to update schema setting.
	 */
	public function handle_schema_setting_update() {
		// Check nonce.
		if ( ! isset( $_POST['nonce'] ) || ! wp_verify_nonce( $_POST['nonce'], 'reviewapp_admin_nonce' ) ) {
			wp_send_json_error( __( 'Invalid security token', 'reviewapp-reviews' ), 403 );
		}

		// Check permissions.
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Insufficient permissions', 'reviewapp-reviews' ), 403 );
		}

		// Get and validate the value.
		$enable_schema = isset( $_POST['enable_schema'] ) && $_POST['enable_schema'] === '1';

		// Update the option.
		update_option( 'reviewapp_enable_schema', $enable_schema ? 'yes' : 'no' );

		// Return success.
		wp_send_json_success(
			array(
				'enable_schema' => $enable_schema,
				'message'       => __( 'Schema setting updated successfully', 'reviewapp-reviews' ),
			)
		);
	}

}