<?php
/**
 * Admin settings page for reviewbird.
 *
 * @package reviewbird
 */

namespace reviewbird\Admin;

use reviewbird\Api\Client;

/**
 * Admin settings page.
 */
class Settings {

	/**
	 * Initialize admin hooks.
	 */
	public function __construct() {
		add_action( 'wp_ajax_reviewbird_update_schema_setting', array( $this, 'handle_schema_setting_update' ) );
		add_action( 'admin_notices', array( $this, 'display_oauth_notices' ) );
	}

	/**
	 * Display OAuth success/error notices from transients.
	 */
	public function display_oauth_notices() {
		$screen = get_current_screen();
		if ( ! $screen || 'settings_page_reviewbird-settings' !== $screen->id ) {
			return;
		}

		// Check for OAuth error.
		$error = get_transient( 'reviewbird_oauth_error' );
		if ( $error ) {
			?>
			<div class="notice notice-error is-dismissible">
				<p>
					<strong><?php esc_html_e( 'reviewbird Connection Error:', 'reviewbird-reviews' ); ?></strong>
					<?php echo esc_html( $error ); ?>
				</p>
			</div>
			<?php
			delete_transient( 'reviewbird_oauth_error' );
		}

		// Check for OAuth success.
		$success = get_transient( 'reviewbird_oauth_success' );
		if ( $success ) {
			?>
			<div class="notice notice-success is-dismissible">
				<p><?php esc_html_e( 'Successfully connected to reviewbird!', 'reviewbird-reviews' ); ?></p>
			</div>
			<?php
			delete_transient( 'reviewbird_oauth_success' );
		}
	}

	/**
	 * Add admin menu.
	 */
	public function add_admin_menu() {
		add_options_page(
			__( 'reviewbird Settings', 'reviewbird-reviews' ),
			__( 'reviewbird', 'reviewbird-reviews' ),
			'manage_options',
			'reviewbird-settings',
			array( $this, 'render_settings_page' )
		);
	}



	/**
	 * Enqueue admin scripts and styles.
	 */
	public function enqueue_scripts( $hook ) {
		if ( 'settings_page_reviewbird-settings' !== $hook ) {
			return;
		}

		// Load asset dependencies from .asset.php file generated by @wordpress/scripts
		$asset_file = REVIEWBIRD_PLUGIN_DIR . 'assets/build/admin.asset.php';
		$asset_data = file_exists( $asset_file ) ? include $asset_file : array( 'dependencies' => array(), 'version' => REVIEWBIRD_VERSION );

		wp_enqueue_script(
			'reviewbird-admin',
			REVIEWBIRD_PLUGIN_URL . 'assets/build/admin.js',
			$asset_data['dependencies'],
			$asset_data['version'],
			true
		);

		wp_localize_script(
			'reviewbird-admin',
			'reviewbirdAdmin',
			array(
				'restUrl'      => rest_url( 'reviewbird/v1' ),
				'nonce'        => wp_create_nonce( 'reviewbird_admin_nonce' ),
				'apiUrl'       => reviewbird_get_api_url(),
				'ajaxUrl'      => admin_url( 'admin-ajax.php' ),
				'enableSchema' => get_option( 'reviewbird_enable_schema', 'yes' ) === 'yes',
			)
		);

		wp_enqueue_style(
			'reviewbird-admin',
			REVIEWBIRD_PLUGIN_URL . 'assets/build/admin.css',
			array(),
			$asset_data['version']
		);
	}

	/**
	 * Render the settings page.
	 */
	public function render_settings_page() {
		?>
		<div class="wrap">
			<div id="reviewbird-settings-root"></div>
		</div>
		<?php
	}

	/**
	 * Handle AJAX request to update schema setting.
	 */
	public function handle_schema_setting_update() {
		// Check nonce.
		if ( ! isset( $_POST['nonce'] ) || ! wp_verify_nonce( $_POST['nonce'], 'reviewbird_admin_nonce' ) ) {
			wp_send_json_error( __( 'Invalid security token', 'reviewbird-reviews' ), 403 );
		}

		// Check permissions.
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Insufficient permissions', 'reviewbird-reviews' ), 403 );
		}

		// Get and validate the value.
		$enable_schema = isset( $_POST['enable_schema'] ) && $_POST['enable_schema'] === '1';

		// Update the option.
		update_option( 'reviewbird_enable_schema', $enable_schema ? 'yes' : 'no' );

		// Return success.
		wp_send_json_success(
			array(
				'enable_schema' => $enable_schema,
				'message'       => __( 'Schema setting updated successfully', 'reviewbird-reviews' ),
			)
		);
	}

}